<?php


use Phinx\Seed\AbstractSeed;

class ProductSeeder extends AbstractSeed
{
    public function run()
    {
        $data = [
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 1',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '4000',
                'net_price'    => '5000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 2',
                'color_id'    => '2',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '4400',
                'net_price'    => '2300',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 3',
                'color_id'    => '3',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '6600',
                'net_price'    => '3300',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 4',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 5',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 6',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 7',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 8',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 9',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 10',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 11',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 12',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 13',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 14',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 15',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 16',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 17',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 18',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 19',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'gross_price'    => '2000',
                'net_price'    => '1000',
                'images_m'    => 'sample_1.jpg',
                'images_s'    => 'sample_2.jpg',
                'product_name'    => 'test product 20',
                'color_id'    => '1',
                'created_at' => date('Y-m-d H:i:s'),
            ]
        ];

        $posts = $this->table('products');
        $posts->insert($data)
            ->save();
    }
}
